// app/api/symbols/route.js
import { NextResponse } from 'next/server';

// GERÇEK BINANCE COIN LİSTESİ (Web'den bulduğun)
const REAL_BINANCE_COINS = [
  'BTCUSDT', 'ETHUSDT', 'BTCUSD', 'SOLUSDT', 'XRPUSDT', 'ZECUSDT', 'ETHUSD', 'DOGEUSDT', 'BNBUSDT', 'ADAUSDT', 
  'STRKUSDT', 'LTCUSDT', 'DASHUSDT', 'LINKUSDT', 'SUIUSDT', 'AVAXUSDT', 'NEARUSDT', 'ICPUSDT', 'ETHBTC', 'FILUSDT', 
  'UNIUSDT', 'DOTUSDT', 'FETUSDT', 'SOLUSD', 'PEPEUSDT', 'TAOUSDT', 'ASTERUSDT', 'ENAUSDT', 'ZENUSDT', 'XRPUSD', 
  'AAVEUSDT', 'ARBUSDT', 'HBARUSDT', 'ZKUSDT', 'APTUSDT', 'SHIBUSDT', 'TRUMPUSDT', 'TRXUSDT', 'BTCUSDC', 'OPUSDT', 
  'CAKEUSDT', 'WLDUSDT', 'ATOMUSDT', 'SEIUSDT', 'INJUSDT', 'RENDERUSDT', 'PENGUUSDT', 'XLMUSDT', 'CRVUSDT', 'ETCUSDT', 
  'GALAUSDT', 'BCHUSDT', 'XPLUSDT', 'ALGOUSDT', 'WIFUSDT', 'XVGUSDT', 'DYDXUSDT', 'TIAUSDT', 'SUSDT', 'BONKUSDT', 
  'LDOUSDT', 'TONUSDT', 'BNBUSD', 'ROSEUSDT', 'ADAUSD', 'TRBUSDT', 'VIRTUALUSDT', 'FLOKIUSDT', 'PENDLEUSDT', 'VETUSDT', 
  'NOTUSDT', 'JUPUSDT', 'DCRUSDT', 'WLFIUSDT', 'EIGENUSDT', 'SOLBTC', 'ARUSDT', 'GRTUSDT', 'ETHFIUSDT', 'ETHUSDC', 
  'POLUSDT', 'DOGEUSD', 'XRPBTC', 'PAXGUSDT', 'MINAUSDT', 'LAUSDT', 'BTCEUR', 'MANTAUSDT', 'SANDUSDT', 'PUMPUSDT', 
  'RESOLVUSDT', 'SNXUSDT', 'GIGGLEUSDT', 'APEUSDT', 'THETAUSDT', '1INCHUSDT', 'SOLUSDC', 'QNTUSDT', 'BATUSDT', 'RUNEUSDT', 
  'SUSHIUSDT', 'CHZUSDT', 'LINEAUSDT', 'ZROUSDT', 'RAYUSDT', 'JASMYUSDT', 'ZECUSD', 'MANAUSDT', 'COTIUSDT', 'DUSKUSDT', 
  'AXSUSDT', 'LTCBTC', 'ONDOUSDT', 'ALLOUSDT', 'IMXUSDT', 'EGLDUSDT', 'ARKMUSDT', 'WUSDT', 'LINKUSD', 'NEOUSDT', 'LSKUSDT', 
  'LTCUSD', 'SUIUSD', 'SYRUPUSDT', 'DOGSUSDT', 'XRPUSDC', 'IOTAUSDT', 'AVNTUSDT', 'KAVAUSDT', 'LUNCUSDT', 'CFXUSDT', 
  'TWTUSDT', 'OMUSDT', 'ORDIUSDT', 'RSRUSDT', 'EDUUSDT', 'PYTHUSDT', 'ONEUSDT', 'XTZUSDT', 'STXUSDT', 'MMTUSDT', 'ALCXUSDT', 
  'AVAXUSD', 'HBARUSD', 'ZECBTC', 'SOLETH', 'NEIROUSDT', 'ZILUSDT', 'PNUTUSDT', 'BIOUSDT', 'XRPEUR', 'COMPUSDT', 'ENSUSDT', 
  'KITEUSDT', 'FORMUSDT', 'SCRTUSDT', 'LUNAUSDT', 'MEMEUSDT', 'FLUXUSDT', 'ADABTC', 'KSMUSDT', 'FFUSDT', 'BNBBTC', 'AIXBTUSDT', 
  'JTOUSDT', 'DGBUSDT', 'XNOUSDT', 'API3USDT', 'ETHEUR', 'HOTUSDT', 'BOMEUSDT', 'WOOUSDT', 'IOUSDT', 'GMTUSDT', 'PIVXUSDT', 
  'BERAUSDT', 'ALICEUSDT', '0GUSDT', 'MUBARAKUSDT', 'NEARUSD', 'FETUSD', 'WCTUSDT', 'DOTUSD', 'MAGICUSDT', 'XAIUSDT', 'ILVUSDT', 
  'ENJUSDT', 'AUDIOUSDT', 'SUPERUSDT', 'PEOPLEUSDT', 'NILUSDT', 'SLPUSDT', 'DOGEBTC', 'ICPUSD', 'SKLUSDT', 'C98USDT', 'CELOUSDT', 
  'ALTUSDT', 'LPTUSDT', 'GLMRUSDT', 'CHRUSDT', 'RVNUSDT', 'BTCBRL', 'STOUSDT', 'ACHUSDT', 'NMRUSDT', 'PARTIUSDT', 'REZUSDT', 
  'SAGAUSDT', 'CVXUSDT', 'TAOUSD', 'AEVOUSDT', 'OGUSDT', 'MASKUSDT', 'BNBUSDC', 'AIUSDT', 'BABYUSDT', 'KAITOUSDT', 'IDUSDT', 
  'BEAMXUSDT', 'RLCUSDT', 'USUALUSDT', 'LINKBTC', 'DASHUSD', 'ANKRUSDT', 'USDTARS', 'GMXUSDT', 'PLUMEUSDT', 'SOMIUSDT', 'FLOWUSDT', 
  'GLMUSDT', 'TAOBTC', 'HFTUSDT', 'SPKUSDT', 'DENTUSDT', 'ZRXUSDT', 'LRCUSDT', 'STORJUSDT', 'CKBUSDT', 'PYRUSDT', 'YGGUSDT', 
  'OGNUSDT', 'YFIUSDT', 'TURBOUSDT', 'EPICUSDT', 'SUIBTC', 'ARPAUSDT', 'FXSUSDT', 'PHAUSDT', 'RAREUSDT', 'PHBUSDT', 'PORTALUSDT', 
  'PIXELUSDT', 'METUSDT', 'HOOKUSDT', 'MOVRUSDT', 'SOLEUR', 'TRXUSD', 'BANKUSDT', 'YBUSDT', '2ZUSDT', 'DYMUSDT', 'FUNUSDT', 
  'FTTUSDT', 'COOKIEUSDT', 'BANANAUSDT', 'SFPUSDT', 'SXPUSDT', 'IOTXUSDT', 'SUIUSDC', 'HMSTRUSDT', 'BBUSDT', 'HYPERUSDT', 
  'CYBERUSDT', 'UNIUSD', 'STRKTRY', 'TURTLEUSDT', 'UMAUSDT', 'MOVEUSDT', 'NEXOUSDT', 'USDTTRY', 'QTUMUSDT', 'METISUSDT', 'BELUSDT', 
  'CELRUSDT', 'AAVEUSD', 'KERNELUSDT', 'NXPCUSDT', 'VANRYUSDT', 'AMPUSDT', 'FIDAUSDT', 'AVAUSDT', 'XLMUSD', 'WLDUSD', 'USTCUSDT', 
  'VETUSD', 'ONTUSDT', 'ADAUSDC', 'STGUSDT', 'LTCUSDC', 'XRPETH', 'MDTUSDT', 'LINKUSDC', 'MLNUSDT', 'AXLUSDT', 'LISTAUSDT', 
  'AVAXBTC', 'SANTOSUSDT', 'RDNTUSDT', 'DASHBTC', 'PEPEUSDC', 'ASTRUSDT', 'VANAUSDT', 'DODOUSDT', 'DIAUSDT', 'HIGHUSDT', 'FISUSDT', 
  'AUCTIONUSDT', 'VTHOUSDT', 'KNCUSDT', 'BLURUSDT', 'TLMUSDT', 'BTCJPY', 'JOEUSDT', 'MBOXUSDT', 'DEGOUSDT', 'EDENUSDT', 'TFUELUSDT', 
  'AUSDT', 'DOGEUSDC', 'ENAUSD', 'LAYERUSDT', 'OPENUSDT', 'LQTYUSDT', 'BCHBTC', 'MAVUSDT', 'FILUSD', 'AWEUSDT', 'SCRUSDT', 
  'SAPIENUSDT', 'ENSOUSDT', 'BCHUSD', 'SHELLUSDT', 'ALPINEUSDT', 'DEXEUSDT', 'NEARBTC', 'INITUSDT', 'SKYUSDT', 'DOTBTC', 'WINUSDT', 
  'ERAUSDT', 'SAHARAUSDT', 'TAOUSDC', 'XECUSDT', 'PROVEUSDT', 'ACTUSDT', 'ATAUSDT', 'ZECETH', 'SUNUSDT', 'SPELLUSDT', 'CTKUSDT', 
  '1000SATSUSDT', 'ASTERUSDC', 'TUTUSDT', 'NFPUSDT', 'CVCUSDT', 'BARDUSDT', 'GUNUSDT', 'THEUSDT', 'CTSIUSDT', 'XRPTRY', 'COWUSDT', 
  'XVSUSDT', 'ATOMUSD', 'HUMAUSDT', 'IOSTUSDT', 'ZKCUSDT', 'TSTUSDT', 'MTLUSDT', 'SYSUSDT', 'PEPETRY', 'USDCUSDT', 'ACEUSDT', 
  'LUMIAUSDT', 'BICOUSDT', 'TRUUSDT', 'ZECUSDC', 'SSVUSDT', 'SYNUSDT', 'FETBTC', 'STRKUSDC', 'ICPBTC', 'ICXUSDT', 'ETHTRY', 
  'JSTUSDT', 'RADUSDT', 'MITOUSDT', 'ASRUSDT', 'ADAEUR', 'MORPHOUSDT', 'IDEXUSDT', 'SCUSDT', 'UNIBTC', 'INJUSD', 'FILBTC', 
  'MIRAUSDT', 'TRXBTC', 'ACAUSDT', 'CETUSUSDT', 'BTTCUSDT', 'CRVUSD', 'RPLUSDT', 'ALGOUSD', 'SANDUSD', 'XRPJPY', 'USDTBRL', 
  'TKOUSDT', 'CUSDT', 'PROMUSDT', 'NKNUSDT', 'POLYXUSDT', 'EURUSDT', 'NOMUSDT', 'BROCCOLI714USDT', 'AAVEBTC', 'FUSDT', 'ZBTUSDT', 
  'CAKEUSD', 'GTCUSDT', 'RONINUSDT', 'ARKUSDT', '1MBABYDOGEUSDT', 'WLDUSDC', 'AGLDUSDT', 'ENAUSDC', 'PAXGUSDC', 'FETTRY', 'ETHEURI', 
  'FETUSDC', 'GASUSDT', 'HBARUSDC', 'OSMOUSDT', 'REDUSDT', 'PUNDIXUSDT', 'ICPUSDC', 'EGLDUSD', 'NEARUSDC', 'SOLVUSDT', 'TNSRUSDT', 
  'TOWNSUSDT', 'DATAUSDT', 'VELODROMEUSDT', 'AVAXTRY', 'STRAXUSDT', 'AAVEUSDC', 'CGPTUSDT', 'ATMUSDT', 'BNTUSDT', 'WALUSDT', 'TUSDT', 
  'PONDUSDT', 'KAIAUSDT', 'RIFUSDT', 'HEMIUSDT', 'SCRTUSD', 'NTRNUSDT', 'CRVBTC', 'ORCAUSDT', 'BTCTRY', 'EIGENTRY', 'INJBTC', 
  'SIGNUSDT', 'GPSUSDT', 'THETAUSD', 'ADXUSDT', 'BARUSDT', 'DOGEJPY', 'EULUSDT', 'OXTUSDT', 'APTUSD', 'ZENUSD', 'LINKETH', 'COSUSDT', 
  'ALLOTRY', 'BNBEUR', 'DOGETRY', 'SOLJPY', 'XLMBTC', 'PAXGUSD', 'IOTAUSD', 'VICUSDT', 'HBARBTC', 'RUNEUSD', 'BNBETH', 'ARDRUSDT', 
  'DOTUSDC', 'NEIROTRY', 'MEUSDT', 'ETCUSD', 'BATUSD', 'FILUSDC', 'BANANAS31USDT', 'AVAXUSDC', 'ONGUSDT', 'ZKUSDC', 'SXTUSDT', 
  'POWRUSDT', 'CHESSUSDT', 'ARBBTC', 'FARMUSDT', 'ZKTRY', '1000CATUSDT', 'HIVEUSDT', 'ACXUSDT', 'ETHJPY', 'ETHFDUSD', 'GRTUSD', 
  'ADAETH', 'QNTUSD', 'GNOUSDT', 'ETCBTC', 'ENATRY', 'HEIUSDT', 'MANAUSD', 'XRPBNB', 'UTKUSDT', 'BMTUSDT', 'STEEMUSDT', 'VOXELUSDT', 
  'KMNOUSDT', 'SOPHUSDT', 'ZENUSDC', 'DOGEEUR', 'RENDERBTC', 'ANIMEUSDT', 'BONKTRY', 'GNSUSDT', 'WAXPUSDT', 'A2ZUSDT', 'IQUSDT', 
  'PSGUSDT', 'REQUSDT', 'VIRTUALUSDC', 'HOLOUSDT', 'DOLOUSDT', 'RENDERUSD', 'BTCTUSD', 'QIUSDT', 'BIFIUSDT', 'ATOMBTC', 'GUSDT', 
  'JUVUSDT', 'ACMUSDT', 'UNIUSDC', 'FORTHUSDT', 'SOLTRY', 'SEIBTC', 'LTCETH', 'ASTERTRY', 'WLFIUSDC', 'ETHFITRY', 'ENABTC', 
  'PENGUUSDC', 'FIOUSDT', 'APTBTC', 'HOMEUSDT', '1000CHEEMSUSDT', 'RESOLVTRY', 'LAZIOUSDT', 'QNTBTC', 'FDUSDUSDT', 'ZENBTC', 'REIUSDT', 
  'ALGOBTC', 'DASHUSDC', 'FLOKITRY', 'DUSDT', 'CAKEBTC', 'TONUSD', 'WANUSDT', 'OPBTC', 'SEIUSD', 'ZKUSD', 'ETHBRL', 'DOTEUR', 
  'AVAXETH', 'ARUSD', 'ALGOUSDC', 'NEWTUSDT', 'CHZUSD', 'ATOMUSDC', 'MINATRY', 'TRUMPUSDC', 'PUMPUSDC', 'XNOBTC', 'PLUMEUSDC', 
  'PENGUTRY', 'WIFUSDC', 'BCHUSDC', 'AXSUSD', 'XTZBTC', 'ZKBTC', 'BATBTC', 'MBLUSDT', 'HAEDALUSDT', 'CITYUSDT', 'RENDERUSDC', 
  'OPUSD', 'POLUSD', 'PORTOUSDT', 'JUPUSDC', 'STXUSD', 'SEIUSDC', 'ARBUSDC', 'RUNEBTC', 'BTCEURI', 'VETEUR', 'BIGTIMEUSDT', 'DFUSDT', 
  'GHSTUSDT', 'THETABTC', 'QUICKUSDT', 'WLDBTC', 'TIAUSD', 'SUIEUR', 'QKCUSDT', 'ARKMTRY', 'FILTRY', 'GIGGLETRY', 'SOLFDUSD', 
  'WLDTRY', 'FORMTRY', 'VETBTC', 'XPLUSDC', 'LSKUSD', 'RESOLVUSDC', 'GIGGLEUSDC', 'AUDIOTRY', 'SUSD', 'EDUTRY', 'TIABTC', 'USDEUSDT', 
  'XLMUSDC', 'TIATRY', 'SBTC', 'LDOUSD', 'LATRY', 'ARBTRY', 'SUSDC', 'TRBTRY', 'PENDLEBTC', 'SOLBNB', 'SHIBUSDC', 'BIOTRY', 'LINKEUR', 
  'SNXUSD', 'NEOUSD', 'SYRUPUSDC', 'EURIUSDC', 'TONUSDC', 'LTCEUR', 'EGLDBTC', 'PENDLEUSD', 'AVAXEUR', 'PNUTTRY', 'OMTRY', 'BELTRY', 
  'SHIBTRY', 'XVGTRY', 'INJUSDC', 'IOTABTC', 'ROSEBTC', 'PIVXBTC', 'WLFITRY', 'ADATRY', 'EURUSDC', 'BONKUSDC', 'PIVXUSD', 'TRXUSDC', 
  'ONDOUSDC', 'WBTCUSDT', 'CHZTRY', 'SANTOSTRY', 'LINEAUSDC', 'AVNTUSDC', 'LUNCTRY', 'WIFUSD', 'PEPEEUR', 'API3TRY', 'XRPFDUSD', 
  'ADAJPY', 'XRPBRL', 'DOGEFDUSD', 'ICPEUR', 'TRUMPTRY', 'POLUSDC', 'AAVEETH', 'TONBTC', 'IMXBTC', 'ARBTC', 'ROSETRY', 'SOLBRL', 
  'AVNTTRY', 'HOTTRY', 'LTCTRY', 'ARBETH', '1000SATSUSDC', 'SANDBTC', 'ALPINETRY', 'MAGICTRY', 'TIAUSDC', 'TRBBTC', 'ENJUSD', 
  'POLBTC', 'FETFDUSD', 'BNBFDUSD', 'DYDXBTC', 'NEAREUR', 'LSKBTC', 'SNXBTC', 'NEOBTC', 'BNSOLUSDT', 'MEMETRY', 'BNBTRY', 'GLMUSD', 
  'SUSHIUSD', '0GTRY', 'EDENTRY', 'AEURUSDT', '1INCHBTC', 'SNXTRY', 'MMTUSDC', 'KITEUSDC', 'PENDLEUSDC', 'WBETHUSDT', 'APTUSDC', 
  'BNBJPY', 'SCRTBTC', 'TRBUSD', 'ROSEUSDC', 'XLMEUR', 'MANABTC', 'USD1USDT', 'GRTBTC', 'LDOBTC', 'PAXGTRY', 'TURTLETRY', 'CHZBTC', 
  'UNIETH', 'MMTTRY', 'BBTRY', 'SUITRY', 'TFUELUSD', 'COTIUSD', 'XTZUSD', 'XUSDUSDT', 'AXSBTC', 'BIOUSDC', 'BTCZAR', 'TRBUSDC', 
  'FLUXUSD', 'PARTITRY', 'OPUSDC', 'WIFTRY', 'WIFBTC', 'BABYUSDC', 'GALATRY', 'IMXUSD', 'BTCPLN', 'AMPTRY', 'POLEUR', 'VIRTUALTRY', 
  'DASHETH', 'LAUSDC', 'SAPIENTRY', 'RAYUSDC', 'SUSHIBTC', 'USDTUAH', 'EURIUSDT', 'APEUSD', 'LDOUSDC', 'LINEATRY', 'BTCARS', 'WBTC', 
  'ALTBTC', 'BTCDAI', 'FFTRY', 'CRVUSDC', 'BANKTRY', 'UNITRY', 'MANTATRY', 'TRXTRY', 'ZRXBTC', 'LUNATRY', 'OPTRY', 'ATMTRY', 'ARUSDC', 
  'MANTABTC', 'NMRBTC', 'STXBTC', 'MINABTC', 'WCTTRY', 'COTIBTC', 'KITETRY', 'SHIBEUR', 'ENJBTC', 'DOTETH', 'HBARTRY', 'QNTUSDC', 
  'XAITRY', 'APEBTC', 'CAKEUSDC', 'DYDXUSD', 'APETRY', 'AIXBTTRY', 'LAYERTRY', 'REZTRY', 'FLOKIUSDC', 'NEXOBTC', 'ZROBTC', 'ROSEUSD', 
  'GALAUSDC', 'EPICUSDC', 'DUSKBTC', 'KSMUSD', 'TUSDUSDT', 'BTTCTRY', 'GLMBTC', 'PHBBTC', 'STRY', 'YBUSDC', 'CFXUSD', 'ICPETH', 
  'KERNELTRY', 'PLUMETRY', 'ADABRL', 'AUDIOUSD', 'NEARETH', 'ICXUSD', 'KAVABTC', 'COMPBTC', 'ICPTRY', 'ORDIBTC', 'INJTRY', 'ALLOUSDC', 
  'CAKEBNB', 'MINAUSD', 'MUBARAKTRY', 'PNUTUSDC', 'USDPUSDT', 'KSMBTC', 'SETH', 'RLCBTC', 'LTCJPY', 'CFXUSDC', 'WCTUSDC', 'NEARTRY', 
  'COTITRY', 'STRKFDUSD', 'ZROUSD', 'ACHTRY', 'LDOTRY', 'ALICETRY', 'EULUSDC', 'AAVETRY', 'MANTAUSD', 'FLUXBTC', 'SPELLTRY', 'TRXETH', 
  'SANDTRY', 'KAVAUSD', 'IOTAUSDC', 'KNCBTC', 'QTUMBTC', 'ICXBTC', 'SUPERUSD', 'EIGENBTC', 'YFIBTC', 'RENDERTRY', 'GPSTRY', 'LINKTRY', 
  'BFUSDUSDT', 'GASUSD', 'JTOTRY', 'ETCUSDC', 'AIXBTUSDC', 'PNUTBTC', 'ZRXUSD', 'SKLTRY', 'EGLDUSDC', 'PYTHUSD', 'XLMTRY', 'LRCUSD', 
  'DOTTRY', 'FLOWBTC', 'TURTLEUSDC', 'GLMRBTC', 'BERABTC', 'COMPUSD', 'JUPTRY', 'NEIROUSDC', 'ARPATRY', 'XVSBTC', 'ARKMBTC', '0GUSDC', 
  'PHBUSD', 'PYTHUSDC', 'ONTUSD', 'SPKUSDC', 'SYSUSD', 'ETCETH', 'IOUSD', 'ENSBTC', 'XVSUSD', 'DUSKUSD', 'SUPERBTC', 'FFUSDC', 'TAOTRY', 
  'QTUMUSD', 'JTOUSDC', 'EIGENUSD', 'PENDLETRY', 'USDCPLN', 'CELOUSD', 'ENSUSD', 'OPETH', 'LINKFDUSD', 'BABYTRY', 'AIUSD', 'IOTRY', 
  'NILTRY', 'OMUSDC', 'CELOBTC', 'RSRUSDC', '2ZUSDC', 'MAVTRY', '1INCHUSD', 'NEXOUSD', 'CGPTUSDC', 'MEMEUSDC', 'USUALTRY', 'SSVBTC', 
  'HEMIUSDC', 'FLOWUSD', 'SHIBBRL', 'ETHTUSD', 'WBTCBTC', '1000SATSTRY', 'TRXEUR', 'WBETHETH', 'FORMUSDC', 'AXSTRY', 'SUIJPY', 'ASRTRY', 
  'OMBTC', 'TLMTRY', 'MUBARAKUSDC', 'PYRUSD', 'XPLTRY', 'ZROTRY', 'ADAFDUSD', 'FDUSDUSDC', 'BANKUSDC', 'MANTAUSDC', 'PIXELTRY', 
  'LINKBRL', 'MORPHOUSDC', 'NOTUSDC', 'SEITRY', 'ACTUSDC', 'CFXBTC', 'PYTHBTC', 'UMAUSDC', 'METTRY', 'BANDUSD', 'SKLBTC', 'STORJBTC', 
  'EGLDEUR', 'NOTTRY', 'GRTTRY', 'PYRBTC', 'APTTRY', 'EIGENUSDC', 'OMUSD', 'BTCMXN', 'ONDOTRY', 'USDTZAR', 'HYPERTRY', 'SKYUSDC', 
  'AEVOBTC', 'SHIBJPY', 'VETUSDC', 'MOVEUSD', 'SNXUSDC', 'ALGOTRY', 'USDTMXN', 'ENJTRY', 'AVAUSD', 'BOMETRY', 'SHIBDOGE', 'VELODROMEUSDC', 
  'BROCCOLI714USDC', 'FILETH', 'SKYTRY', 'USDTCOP', 'ABTC', 'LRCBTC', 'ONTBTC', 'POLTRY', 'LPTUSD', 'APTETH', 'PSGTRY', 'REQBTC', 
  'NXPCUSDC', 'SAGABTC', 'LRCTRY', 'ALTUSD', 'CHRUSD', 'YGGUSD', 'ILVBTC', 'HYPERUSDC', 'POWRUSD', 'TONTRY', 'ASTRUSD', 'GMTBTC', 
  'WUSDC', 'ATOMTRY', 'OGNTRY', 'RARETRY', 'ORDIUSDC', 'LPTBTC', 'KAITOTRY', 'MANATRY', 'SOLVTRY', 'PORTALTRY', 'KMNOUSDC', 'PHABTC', 
  'SOMIUSDC', 'WUSD', 'XLMETH', 'OSMOUSDC', 'PNUTUSD', 'PEPEFDUSD', 'CKBUSDC', 'OGNBTC', 'SOLTUSD', 'ASTRBTC', 'OGNUSD', 'RLCUSD', 
  'HMSTRTRY', 'HOTETH', 'SYSBTC', 'UMABTC', 'ACHUSD', 'LTCBRL', 'OGTRY', 'RENDEREUR', 'GASBTC', 'TFUELBTC', 'TURBOTRY', 'NILUSDC', 
  'AXLUSD', 'WBTCETH', 'LTCFDUSD', 'FLUXUSDC', 'JSTBTC', 'BERAUSDC', 'ADXBTC', 'ALTTRY', 'GUNUSDC', 'ZKCTRY', 'ALTUSDC', 'API3USDC', 
  'BANDBTC', 'EDENUSDC', 'AUDIOBTC', 'PHBTRY', 'ZROUSDC', 'MTLBTC', 'SAGAUSD', 'SLPTRY', 'YGGBTC', 'BCHFDUSD', 'IOBTC', 'CYBERTRY', 
  'SYRUPTRY', 'LINKJPY', 'VANATRY', 'ARTRY', 'ETHFIUSDC', 'ETHPLN', 'SANDUSDC', 'TUTUSDC', 'API3BTC', 'BANANAS31USDC', 'ORDIUSD', 
  'RUNEETH', 'DYDXTRY', 'ERATRY', 'YFIUSD', 'AEVOTRY', 'LAYERUSDC', 'AVAXFDUSD', 'CHRBTC', 'POWRBTC', 'SAPIENUSDC', 'ARKMUSD', 'BARTRY', 
  'GMTUSD', 'SKYBTC', 'RONINUSD', 'GLMRUSD', 'ATOMETH', 'CETUSTRY', 'JOEBTC', 'COOKIEUSDC', 'ADABNB', 'BELBTC', 'PYTHTRY', 'TREETRY', 
  'VETETH', 'ANKRTRY', 'JASMYTRY', 'SSVUSD', 'XVGUSDC', 'MOVRUSD', 'RUNEUSDC', 'RVNTRY', 'SXPBTC', 'BICOBTC', 'LTCBNB', 'PHATRY', 
  'LUMIATRY', 'STOUSDC', 'ARBEUR', 'BBUSD', 'POLYXTRY', 'RAREUSDC', 'DIABTC', 'FIDATRY', 'METUSDC', 'CRVTRY', 'OXTBTC', 'TURBOUSDC', 
  'AITRY', 'AUCTIONBTC', 'TRXJPY', 'NMRUSDC', 'ACHBTC', 'HUMAUSDC', 'LAYERBTC', 'RAYTRY', 'ZKCUSDC', 'KERNELUSDC', 'THETAUSDC', 
  'DYDXUSDC', 'COWTRY', 'PEPEJPY', 'TRUMPJPY', 'TSTUSDC', 'USDCBRL', 'GALAEUR', 'KAITOBTC', 'LPTTRY', 'BOMEUSDC', 'ETCTRY', 'KNCUSD', 
  'NEARJPY', 'BCHEUR', 'OGBTC', 'PHAUSD', 'UMATRY', 'SUPERTRY', 'ARPABTC', 'IDBTC', 'SCRBTC', 'POLETH', 'REZUSDC', 'SCRUSD', 'FUSDC', 
  'GALAETH', 'PORTALUSD', 'USDTDAI', 'SFPBTC', 'IOUSDC', 'EGLDETH', 'NEOTRY', 'PARTIUSDC', 'SOMITRY', '1MBABYDOGEFDUSD', 'MBOXTRY', 
  'MOVRBTC', 'RDNTTRY', 'DOGEBRL', 'FFBNB', 'GRTETH', 'GRTEUR', 'HEMITRY', 'KAITOUSDC', 'ETHDAI', 'NMRUSD', 'PLUMEFDUSD', 'USTCTRY', 
  'ENSTRY', 'ONTTRY', 'OPENTRY', 'TRXXRP', 'FDUSDTRY', 'SLPETH', 'VANRYTRY', 'ACATRY', 'BANANABTC', 'RAREBTC', 'AXLTRY', 'PEPEBRL', 
  'RSRTRY', 'VANAUSDC', 'PEOPLEFDUSD', 'THETRY', 'SKLUSD', 'CTSIBTC', 'MAGICUSD', 'OXTUSD', 'STOTRY', 'AUSD', 'NEWTUSDC', 'APTEUR', 
  'CHESSUSDC', 'ETHMXN', 'MOVETRY', 'WIFFDUSD', 'CAKETRY', 'HIVEBTC', 'ENSUSDC', 'SHELLTRY', 'TRXBNB', 'DOLOTRY', 'NXPCTRY', 'SAGAUSDC', 
  'STGBTC', 'VETTRY', 'GMXUSDC', 'USUALUSDC', 'HFTBTC', 'RIFBTC', 'SANTOSBTC', 'APEUSDC', 'AWEBTC', 'BMTFDUSD', 'RADTRY', 'SXPUSD', 
  'DOGSUSDC', 'MITOUSDC', 'ATOMEUR', 'BARDUSDC', 'ETHFIFDUSD', 'HOLOUSDC', 'PIXELUSDC', 'COWUSDC', 'INJETH', 'MAGICBTC', 'AVABTC', 
  'HOLOTRY', 'NFPBTC', 'OPENUSDC', 'SPKTRY', '1000CATUSDC', 'ERAUSDC', 'SEIFDUSD', 'SIGNTRY', 'AUSDC', 'TWTUSDC', 'SUIFDUSD', 'MIRATRY', 
  'GALABRL', 'HMSTRUSDC', 'MEBTC', 'SOLMXN', 'DOLOFDUSD', 'STXUSDC', 'BNBBRL', 'DOGSTRY', 'AVAXBRL', 'BARDTRY', 'BLURTRY', 'EULTRY', 
  'LINKBNB', 'SCRTRY', 'STEEMBTC', 'USDCTRY', 'CUSDC', 'JUVTRY', 'STORJTRY', 'AXLBTC', 'BMTUSDC', 'SEIJPY', '1000CATTRY', 'AIBTC', 
  'HUMATRY', 'PORTALBTC', 'SUNTRY', 'SXPTRY', 'TUSDC', 'USDTPLN', 'XRPMXN', 'ARDRUSD', 'POLBRL', 'STRAXBTC', 'YGGUSDC', 'ADXUSD', 
  'ANIMETRY', 'BERAUSD', 'DODOBTC', 'FLOKIFDUSD', 'HOMETRY', 'STXTRY', 'TSTTRY', 'BNSOLSOL', 'ETHARS', 'REDUSDC', 'FIDABTC', 'FISBTC', 
  'NEARBRL', 'NOMTRY', 'DENTTRY', 'ARDRBTC', 'BCHJPY', 'NOMUSDC', 'WANUSD', 'KAIAUSDC', 'TWTTRY', 'GTRY', 'STORJUSD', 'WANBTC', 
  'YBTRY', 'INITTRY', 'MIRAUSDC', 'SKYUSD', 'COSTRY', 'FIDAUSD', 'GRTUSDC', 'IMXUSDC', 'TURTLEFDUSD', 'GMTTRY', 'MAVBTC', 'MEUSD', 
  'TRUMPEUR', 'ACETRY', 'BBBTC', 'CTKBTC', 'INITUSDC', 'IOTAETH', 'NEIROFDUSD', 'POLJPY', 'REQUSD', 'VANRYUSDC', 'AEVOUSD', 'CATIUSDC', 
  'DODOUSD', 'JOEUSD', 'METRY', 'MTLUSD', 'ONGUSD', 'SAHARAUSDC', 'SOLARS', 'AGLDBTC', 'CYBERUSD', 'DOTBRL', 'JSTUSD', 'WLFIEUR', 
  'AUCTIONUSD', 'BNBTUSD', 'ORDITRY', 'ZILTRY', 'ANIMEUSDC', 'ARKTRY', 'BEAMXUSDC', 'FTRY', 'RPLUSDC', 'BANANATRY', 'CYBERBTC', 
  'ENABRL', 'STEEMUSD', 'WBTCUSD', 'CATITRY', 'CTRY', 'DIAUSD', 'POLYXBTC', 'SHELLUSD', 'PORTOTRY', 'SOPHUSDC', 'ATRY', '2ZTRY', 
  'HBARBNB', 'NFPTRY', 'BELUSD', 'CETUSUSDC', 'WTRY', '1MBABYDOGETRY', 'DENTETH', 'EGLDRON', 'SHELLUSDC', 'WIFEUR', 'ETHZAR', 'HFTUSD', 
  'TOWNSTRY', 'TREEUSDC', 'ZBTUSDC', 'JUVUSDC', 'ONETRY', 'ORCAUSDC', 'ZBTTRY', 'IOTATRY', 'WAXPBTC', 'ALLOBNB', 'ARKMUSDC', 'LAYERUSD', 
  'SCETH', 'FORTHBTC', 'MAVUSD', 'CHZUSDC', 'DYMTRY', 'HIVEUSD', 'HIVEUSDC', 'PENDLEFDUSD', 'SHIBFDUSD', 'WALUSDC', 'WLDEUR', 'DOLOUSDC', 
  'EUREURI', 'MASKTRY', 'BTCUAH', 'SEUR', 'TAOFDUSD', '1000CHEEMSUSDC', 'APTJPY', 'AVAXBNB', 'BCHTRY', 'HIGHTRY', 'KSMTRY', 'ONGBTC', 
  'BBUSDC', 'KAITOUSD', 'SKLUSDC', 'LPTUSDC', 'PEOPLEUSDC', 'POLYXUSD', 'PROVETRY', 'SFPUSD', 'BERATRY', 'GMTUSDC', 'HEIBTC', 'LISTAUSDC', 
  'SUSHIUSDC', 'FISUSD', 'NFPUSD', 'RONINBTC', 'XPLBNB', 'CFXTRY', 'CTSIUSD', 'GPSUSDC', 'NOTFDUSD', 'SUIBNB', 'BANANAUSDC', 'CITYTRY', 
  'ENSOTRY', 'GUNTRY', 'ONTUSDC', 'PHAUSDC', 'CTKUSD', 'PROVEUSDC', 'REDUSD', 'ILVUSDC', 'LISTATRY', 'PENGUFDUSD', 'SYNUSDC', 'ZILETH', 
  'AWEUSD', 'BMTTRY', 'GALAFDUSD', 'IOTXETH', 'PEOPLETRY', '1MBABYDOGEUSDC', 'ARPAUSD', 'AXSUSDC', 'FETBNB', 'THEUSDC', 'FUNUSDC', 
  'NTRNTRY', 'RONINTRY', 'SIGNUSDC', 'WCTFDUSD', 'DOTBNB', 'ORCATRY', 'STEEMUSDC', 'STGUSD', 'SUSHITRY', 'SXTUSDC', 'BNBARS', 'ICPFDUSD', 
  'MAVUSDC', 'SOMIFDUSD', 'A2ZUSDC', 'COMPTRY', 'METISTRY', 'RAREUSD', 'REDBTC', 'WAXPUSD', 'XLMJPY', 'XRPTUSD', 'ZKFDUSD', 'ADXETH', 
  'NEARFDUSD', 'ACXUSDC', 'BEAMXTRY', 'BFUSDUSDC', 'TONFDUSD', 'AUCTIONTRY', 'BANANAUSD', 'BTCRON', 'AGLDUSD', 'DFUSDC', 'GMTEUR', 
  'MANAETH', 'RVNUSDC', 'XAIUSDC', 'NMRTRY', 'MOVEUSDC', 'DTRY', 'SXTTRY', 'TNSRTRY', 'ACXTRY', 'COMPUSDC', 'INJFDUSD', 'RLCETH', 
  'SHELLBTC', 'ACHUSDC', 'HBARFDUSD', 'HOMEUSDC', 'TLMUSDC', 'VICTRY', 'XECTRY', 'AXSETH', 'EULBNB', 'MITOTRY', 'TNSRUSDC', 'BLURUSDC', 
  'ENAFDUSD', 'ENJUSDC', 'IDTRY', 'NEWTTRY', 'THETATRY', 'WALTRY', 'MANTAFDUSD', 'STRAXUSD', 'TRUMPFDUSD', 'USDCRON', 'AUCTIONUSDC', 
  'HEIUSDC', 'NEARBNB', 'ARBTUSD', 'BONKFDUSD', 'CYBERUSDC', 'LABNB', 'UTKUSDC', 'BCHBNB', 'MOVRTRY', 'TOWNSUSDC', 'IDEXUSDC', 
  'LISTAFDUSD', 'PYTHFDUSD', 'STRAXTRY', 'SUIBRL', 'HAEDALUSDC', 'LRCETH', 'WLDFDUSD', 'CKBTRY', 'QTUMETH', 'SOLVUSDC', 'SOPHTRY', 
  'CVCUSDC', 'FILFDUSD', 'FORTHUSD', 'REDTRY', 'ENSOBNB', 'ETCBNB', 'TIAFDUSD', 'VTHOTRY', '0GFDUSD', 'APTFDUSD', 'CVXUSDC', 'EGLDBNB', 
  'MITOFDUSD', 'POLFDUSD', 'SSVETH', 'WINEUR', '1000SATSFDUSD', 'AEVOUSDC', 'BOMEFDUSD', 'PORTALFDUSD', 'MINAUSDC', 'RENDERFDUSD', 
  'SANTOSUSD', 'SIGNBNB', 'USD1USDC', 'USDCCZK', 'DAIJPY', 'GRTFDUSD', 'JUPFDUSD', 'LPTJPY', 'STEEMETH', 'USDEUSDC', 'HAEDALTRY', 
  'PUNDIXUSDC', 'QTUMUSDC', 'WLFIBRL', '2ZBNB', 'POLBNB', 'PROVEFDUSD', 'RIFUSD', 'CYBERETH', 'EGLDTRY', 'ERABNB', 'SOLVBNB', 'TREEBNB', 
  'TRUTRY', 'XPLFDUSD', 'BBFDUSD', 'BIGTIMEUSDC', 'DOTFDUSD', 'EDENBNB', 'MEUSDC', 'MITOBNB', 'PARTIBNB', 'RENDERBRL', 'SEIBNB', 'XVSBNB', 
  'ZBTFDUSD', 'ARBFDUSD', 'LINEABNB', 'MAGICUSDC', 'MASKUSDC', 'PNUTEUR', 'QTUMTRY', 'WFDUSD', 'AEVOFDUSD', 'HEMIFDUSD', 'LISTABNB', 
  'SFDUSD', 'HEIUSD', 'SSVUSDC', 'CELOTRY', 'GASTRY', 'LAFDUSD', 'MORPHOFDUSD', 'NFPFDUSD', 'OPENBNB', 'SANDFDUSD', 'XLMFDUSD', 
  'ARKMFDUSD', 'CTKBNB', 'CYBERFDUSD', 'HMSTRFDUSD', 'KAITOFDUSD', 'MORPHOBNB', 'PORTALBNB', 'SBNB', 'WCTBNB', 'AAVEFDUSD', 'ATOMFDUSD', 
  'BARDFDUSD', 'HEMIBNB', 'INJBNB', 'MIRABNB', 'PLUMEBNB', 'UNIFDUSD', 'VANAFDUSD', 'BANANABNB', 'BANANAFDUSD', 'GUNBNB', 'HIVETRY', 
  'HOLOBNB', 'WIFBRL', '2ZFDUSD', 'DYDXFDUSD', 'JTOFDUSD', 'LDOFDUSD', 'MMTBNB', 'NEIROJPY', 'PNUTFDUSD', 'TURTLEBNB', 'ZKCBNB', 
  'ZKCFDUSD', 'ALTBNB', 'ALTFDUSD', 'CHZBNB', 'CYBERBNB', 'EDENFDUSD', 'ENABNB', 'GUNFDUSD', 'SAPIENBNB', 'SHELLFDUSD', 'SOLVFDUSD', 
  'YBFDUSD', 'AIBNB', 'DOGSFDUSD', 'LINEAFDUSD', 'NTRNBNB', 'ORDIFDUSD', 'SOMIBNB', 'STOFDUSD', 'TRUMPBRL', 'WLFIUSD1', 'DOLOBNB', 
  'EIGENFDUSD', 'ENSOFDUSD', 'ERAFDUSD', 'FFFDUSD', 'INITFDUSD', 'IOBNB', 'KERNELBNB', 'KITEBNB', 'NEWTFDUSD', 'OPFDUSD', 'ARFDUSD', 
  'BERAFDUSD', 'BIOBNB', 'BIOFDUSD', 'NEWTBNB', 'TOWNSFDUSD', 'WINTRX', '0GBNB', 'ARKMBNB', 'BBBNB', 'ETCFDUSD', 'EULFDUSD', 'IOTXJPY', 
  'KERNELFDUSD', 'LPTBNB', 'MOVEBNB', 'NOMFDUSD', 'PARTIFDUSD', 'PROVEBNB', 'TRXFDUSD', 'WALBNB', 'YBBNB', 'AIFDUSD', 'BARDBNB', 
  'BERABNB', 'BONKBRL', 'ENSFDUSD', 'GPSBNB', 'IOFDUSD', 'MEMEFDUSD', 'OPENFDUSD', 'SAGABNB', 'TREEFDUSD', 'VETBNB', 'ZBTBNB', 'ZROFDUSD', 
  'ACTFDUSD', 'EGLDFDUSD', 'HAEDALBNB', 'HOLOFDUSD', 'LAYERFDUSD', 'MIRAFDUSD', 'REDFDUSD', 'RONINFDUSD', 'SAHARABNB', 'SOPHFDUSD', 
  'STXFDUSD', 'APEFDUSD', 'HAEDALFDUSD', 'MEFDUSD', 'RAYFDUSD', 'SCRFDUSD', 'SIGNFDUSD', 'TOWNSBNB', 'WALFDUSD', 'HUMAFDUSD'
].sort();

export async function GET() {
  try {
    console.log('Trying Binance API...');
    
    const response = await fetch('https://api.binance.com/api/v3/exchangeInfo', {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
      },
      signal: AbortSignal.timeout(10000)
    });
    
    console.log('Binance API Status:', response.status);
    
    if (response.ok) {
      const data = await response.json();
      const symbols = data.symbols || [];
      
      // DAHA AZ STRICT FİLTRELEME
      const usdtPairs = symbols
        .filter(symbol => 
          symbol.symbol.endsWith('USDT') && 
          symbol.status === 'TRADING'
        )
        .map(symbol => symbol.symbol)
        .sort();

      console.log(`Binance API success: ${usdtPairs.length} pairs`);
      
      return NextResponse.json({
        success: true,
        symbols: usdtPairs,
        total: usdtPairs.length,
        timestamp: new Date().toISOString(),
        source: 'binance-api'
      });
    }
    
    throw new Error(`HTTP ${response.status}`);
    
  } catch (error) {
    console.error('Binance API failed, using real coin list:', error);
    
    // Web'den bulduğun gerçek listeyi kullan
    return NextResponse.json({
      success: true,
      symbols: REAL_BINANCE_COINS,
      total: REAL_BINANCE_COINS.length,
      timestamp: new Date().toISOString(),
      source: 'real-fallback-list',
      error: error.message
    });
  }
}